;; peteches/system-services/alloy.scm — Guix service type for Grafana Alloy.

(define-module (peteches system-services alloy)
  #:use-module (guix gexp)
  #:use-module (guix records)
  #:use-module (gnu services)
  #:use-module (gnu services shepherd)
  #:use-module (gnu services base)
  #:use-module (gnu packages admin)
  #:use-module (peteches packages alloy)
  #:use-module (peteches system-services firewall)
  #:export (alloy-configuration
            alloy-configuration?
            render-alloy-river
            alloy-service-type))

;;; ── Record type ──────────────────────────────────────────────────────────

(define-record-type* <alloy-configuration>
  alloy-configuration make-alloy-configuration
  alloy-configuration?
  (package          alloy-configuration-package          (default alloy))
  ;; Hostname label attached to every log line shipped to Loki.
  (hostname         alloy-configuration-hostname)
  (loki-url         alloy-configuration-loki-url
                    (default "http://192.168.51.190:3100/loki/api/v1/push"))
  ;; Port for Alloy's own HTTP UI and metrics endpoint.
  (http-listen-port alloy-configuration-http-listen-port (default 12345))
  ;; Log files to tail.  Globs are accepted (e.g. "tailscaled-*.log").
  (log-files        alloy-configuration-log-files
                    (default (list "/var/log/messages"
                                   "/var/log/prometheus-node-exporter.log"
                                   "/var/log/ntpd.log")))
  (storage-path     alloy-configuration-storage-path     (default "/var/lib/alloy"))
  (log-file         alloy-configuration-log-file         (default "/var/log/alloy.log"))
  ;; Raw River blocks appended verbatim after the generated config.
  (extra-blocks     alloy-configuration-extra-blocks     (default "")))

;;; ── River config rendering ───────────────────────────────────────────────
;;
;; Pure Scheme → string at Guix evaluation time.  No gexps here.

(define (render-path-target path)
  (string-append "    {\"__path__\" = \"" path "\"},\n"))

(define (render-alloy-river config)
  "Render a complete Alloy River config string from an <alloy-configuration>."
  (let* ((loki-url   (alloy-configuration-loki-url config))
         (hostname   (alloy-configuration-hostname config))
         (log-files  (alloy-configuration-log-files config))
         (port       (alloy-configuration-http-listen-port config))
         (extra      (alloy-configuration-extra-blocks config)))
    (string-append
     "// Alloy configuration — generated by Guix\n\n"
     "loki.write \"default\" {\n"
     "  endpoint {\n"
     "    url = \"" loki-url "\"\n"
     "  }\n"
     "}\n\n"
     "local.file_match \"logs\" {\n"
     "  path_targets = [\n"
     (apply string-append (map render-path-target log-files))
     "  ]\n"
     "}\n\n"
     "discovery.relabel \"logs\" {\n"
     "  targets = local.file_match.logs.targets\n"
     "  rule {\n"
     "    target_label = \"hostname\"\n"
     "    replacement  = \"" hostname "\"\n"
     "  }\n"
     "  rule {\n"
     "    target_label = \"job\"\n"
     "    replacement  = \"alloy\"\n"
     "  }\n"
     "  rule {\n"
     "    source_labels = [\"__path__\"]\n"
     "    target_label  = \"filename\"\n"
     "  }\n"
     "}\n\n"
     "loki.source.file \"logs\" {\n"
     "  targets    = discovery.relabel.logs.output\n"
     "  forward_to = [loki.write.default.receiver]\n"
     "}\n"
     (if (string=? extra "") "" (string-append "\n" extra "\n")))))

;;; ── Service extension helpers ────────────────────────────────────────────

(define (alloy-activation config)
  (let ((storage-path (alloy-configuration-storage-path config)))
    #~(begin
        (use-modules (guix build utils))
        (mkdir-p #$storage-path)
        (system* #$(file-append shepherd "/bin/herd")
                 "restart" "alloy"))))

(define (alloy-etc-files config)
  (list `("alloy/config.alloy"
          ,(plain-file "config.alloy" (render-alloy-river config)))))

(define (alloy-shepherd-service config)
  (let* ((pkg          (alloy-configuration-package config))
         (log-file     (alloy-configuration-log-file config))
         (storage-path (alloy-configuration-storage-path config))
         (port         (alloy-configuration-http-listen-port config)))
    (list
     (shepherd-service
      (provision '(alloy))
      (documentation "Grafana Alloy observability collector.")
      (requirement '(networking file-systems))
      (start #~(make-forkexec-constructor
                (list #$(file-append pkg "/bin/alloy")
                      "run"
                      #$(string-append "--server.http.listen-addr=0.0.0.0:"
                                       (number->string port))
                      #$(string-append "--storage.path=" storage-path)
                      "/etc/alloy/config.alloy")
                #:log-file #$log-file))
      (stop #~(make-kill-destructor))))))

(define (alloy-firewall-rules config)
  (nftables-rules
   (input (list (string-append
                 "tcp dport "
                 (number->string (alloy-configuration-http-listen-port config))
                 " accept comment \"alloy\"")))))

(define (alloy-profile config)
  (list (alloy-configuration-package config)))

;;; ── Service type ─────────────────────────────────────────────────────────

(define-public alloy-service-type
  (service-type
   (name 'alloy)
   (description "Grafana Alloy observability collector.")
   (extensions
    (list
     (service-extension activation-service-type    alloy-activation)
     (service-extension etc-service-type           alloy-etc-files)
     (service-extension shepherd-root-service-type alloy-shepherd-service)
     (service-extension firewall-service-type      alloy-firewall-rules)
     (service-extension profile-service-type       alloy-profile)))
   (default-value (alloy-configuration
                   (hostname "localhost")))))
