platform: linux

image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: "1.10"

params:
  BRANCH_NAME:
  AWS_ACCESS_KEY_ID: ((terraform.minio_access_key))
  AWS_SECRET_ACCESS_KEY: ((terraform.minio_secret_key))
  TF_VAR_proxmox_api_token: ((terraform.proxmox_api_token))


run:
  path: sh
  args:
  - -ec
  - |
    git clone https://github.com/peteches/guix \
      --branch "$BRANCH_NAME" \
      --depth 1 \
      repo
    cd repo/infra/terraform
    terraform init
    terraform plan
