restic-password: ENC[AES256_GCM,data:nuJT/UWQ4ZN8hhu5n+ubrK2Mc2u7FZPsIAfLLHwRjMGpf5M2g+gOV/OUikkZ63rYcdUoMpIdwO5FMENn8g4avA==,iv:G7ppmoZ6N9hs1x8J/VLyj9UDhzfJqrUntu0bhpnO5PU=,tag:g/FhjGD1mYVGqS3zkIO9wA==,type:str]
ssh-key: ENC[AES256_GCM,data:wWX8H1n02db38JLBi6z7Y1NMrR3KQLA6y+ajBEbc3mqHLiZA1se1l0qSpho0ZN3UtdcMTFmU3CZJR7ht7J2GOzNdO4OdYxOo1+rNARoga/aP4ytx5uq84RKKXlJzh9mOwohLJp2F/YMAKt5yN8xq40XQkBmp6UMrP0V0ufKtghFNIMPbSxJGgzIT9VMMe0dnuO3rqyEjG8JJ6uXcEdMOgF0YOwEqEkHIMeN6BmFM2ddrCFNP2oyHpkYO4NDouOw58Qu7wVkNAQpdgWAum/oKRuQ5TqSZYri+VOtxaSHUnmXhf62pvWB51JppynmTWDD0TSa/e+KFSeQ8XJX0f7WMBTTCXqxYhulp3tjTqdS1r6d1kY4iL6nbvN2LEID3vJ32R3TYVkXUOVKICVN7y7Gj0rpGy6S4iiYPnatnf66LIk01xkTldaixchffeG7Dc8Bv1AUBqexL82VWaQo78F/9uqF54xZc9pzUEr8yqNvtAcJAWg2K7f4aWDuNMYnjTKGvdc6fRDCAIDtvgClPnPVhTjyuXtLS5MP8KIqbrHMo5lFK1Ws=,iv:PTOHho+gOMvW9z0inDtM5rDaDbSnQqrUhb6zyeweXyA=,tag:l4OKWN3uNTuZMPF17/8bkw==,type:str]
sops:
    age:
        - recipient: age1gd29zcp8xpm92aprc03u8a959zlmavue768gxstxu0ykhxh87e3sywr4jj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T05jTGZsc09TNXJqbHFM
            T1FlRUZMcTZHZHFkQ25weEU3QXJ5a3lnR3k0Cm5kVGNCNEZ6SnRMZ0FVb0V5S3Nq
            akh1NVdjYXdFNTQ1am83azVodk1qRmMKLS0tIEVReVhYUGJjNXgxYWJGS3hNTXR2
            cTkyTjQxbGlkNERGMlVEOTkyZ1BwaDQKG2Z8cK5ZBVCdU9Bc5zuvw5nq1Ll38mwc
            BWwuwalYnVWaFsPS4LREH+4fWi8HVSNWr3LJEG39F8QTA0MUYPDarA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T11:39:13Z"
    mac: ENC[AES256_GCM,data:hv7lzgwjj6m8Edwsbcig+yjIweS6uLwEqgpgGB2sTo3HadeXKLrTUd6ytXLOhoNwZfTRqvBR2MeHGZVkSutDCJ3UjNuK83gIqGkJ5nrwRw3VssRYEDB0kr/rX3K8ow4bS5+/D0XjTCg/GA8hACfb8Blc3slETfMuxf+G5frkqmA=,iv:+pi/eu4BlrouOhxEvkBMDt+SnnFHCzIEt5/38n/gBgE=,tag:heZjoL8HGQx4KES89/8ibQ==,type:str]
    pgp:
        - created_at: "2026-05-27T11:39:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5I9ZVut4Oz4SAQdALe2xDfqWhqu1++uzn9Nm0wjPXWKKNNU3Rh91WajPsnIw
            CMPZ0IAHVQ6/nI9g51ztqS7JanIy00C6NVfHAVtm70Tx6fqSL6mOsKNu+IVoRdNZ
            1GYBCQIQgUT8r1JW/cbL7hZtk4e+dRqHJeQwYhVs4VvJG9QxF5UOB02qWfwbo4LB
            gBKgwMJI/SNCnf3rdFvVD+zQDOyGw2Ea7Vh0Ijeao17tziRMVdVe2SS0fTSDpwo3
            6pCVDpMcqP4=
            =TUin
            -----END PGP MESSAGE-----
          fp: 5FFB7006A36B0AEDE8D08E3753B1E002546A642A
    unencrypted_suffix: _unencrypted
    version: 3.12.2
