password: ENC[AES256_GCM,data:SZLQmToOtCzo4lKy/3ecJX+IAmUbzxVDXc45dfxc0ilpfsrtWI6p2gwa64ccn0V6AWBftllNcq0G16WaM47R8g==,iv:k2m8d0wKQ2JT+X2HuyDM0HGFAn1lEeWdQkewIdeVfys=,tag:/s1DfK/d0H0OEFOMk1VMOQ==,type:str]
ssh-key: ENC[AES256_GCM,data:4yFMsNB1CUt3BlVNFl4BZtljG37d4HMd6KwOe2x5becC2axog7F9ivGSuD28BIo48Cwjc6sRifpfGdZTrlPt8NHvvPAdRZF/IqnTns4u3lKm1tl2WNBS97M0qe2FG8BWN0XmMB5/I6hMca6TSoOUe6ypEElBBlNfUbo3etHVvADwWM4UcGSQOXR84oZX0lIqGKDP62Zr5slpzOSKiRdm7sozu2IvIgv9pZ2qf1Hq9+rFaCMIFEnGtFfij6ohfrbb8jrnPOmLw3mhTrxFXIeBcUrgFhc+yHAPpHLRG4sAdWnhVy8MrQTrBF3E5jNLeQcVKZ/YBXhJ5q8/thPhzmVOgsw5F9hh8+a0dgBazEMnYtcZYkyFr/yExFex5DWo00r3fGf/FHaeupcCpax+rcD+jV049+8FzQoSbGpqpLKLukVCfqeQpnRvuX1yKD7YgQuBtMQmwbzvzAbjRJy5Guy6TFHuwXQIUPMLYQ+KUFqVgMOdZ56O4SbyfclpK9mwfT761/+M7iNDb91CLVg4Sgchi/vGWWLGz953GRYTVRJs2d1i+xY=,iv:6mm6PSU7o5943dc49QZgGT54dktb9jZvwcBX45CHspw=,tag:uNUMmm05YLb/2HO+842GFQ==,type:str]
sops:
    age:
        - recipient: age1gd29zcp8xpm92aprc03u8a959zlmavue768gxstxu0ykhxh87e3sywr4jj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSjRxcW9UZll5WmtFclRQ
            T0c0YkQ3TmU4cDJCUHlmSjNUZUhFVkNnR0g4CkFFTGFwSE44VmhhYjFKMjFiSUF1
            RlNySWtEOG5PSXJlR3I5ZXVaeWl2M1EKLS0tIENUUXU3MG9KMXR5VGZKcTRBUmZV
            UnR3OXZNUUtDL2lvN1Z1alVnY25JVkEKlhH2oZ0SHtXHpztmdd2EGTIkUPxO9XBS
            zjyVcj08bUBHTz4wKOxI+aTmKoOwPrYM1GL+yvdA3FEzr/bMXhyUAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T17:57:41Z"
    mac: ENC[AES256_GCM,data:WRtmM7hQFZC9fINfMXNiN/95gnGn8pBtnQIxX1vtUU4Lo6QuhU2m7lNL5m1oI/2Dn3r0X9r3C+smm4SoMpVeEEMuzB/2Hgn8NGhUlZlZedu2JXVYzF7hMd+3/TFb4WuiYffhZVgIYT0N8Ki37NB2nijUYJq/+vZ2bnw+nRX3MOw=,iv:mFA++oTCumzk2FKh/AbRB/ooh+pFAHy1S+k/YM0lOrM=,tag:r5Twnyu1fZ4XKX+hItWeHQ==,type:str]
    pgp:
        - created_at: "2026-05-28T17:57:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5I9ZVut4Oz4SAQdARqbYk4XF+bbnZAUscKgKwfwxVVfZbY9RS8oKtbF8VSww
            LAMdsVjaaPFaGuZ13czvzwmFefKvzun60YmkJ4rX8poHsJRKMHPSJnwR1AY7JSB1
            1GYBCQIQ8hA4GK1l7rWjjNLO8ooPVrsVCzXImA9/F/EyzGLVTrRiJYAEZdq2pfkX
            zmkDG6RuovpxqvYzOKnAUFTUsKQhyHI6vtjWVi8PN5wZdsc1O5OkUw7HzbnmDORI
            41dpjrnPT2o=
            =QiCb
            -----END PGP MESSAGE-----
          fp: 5FFB7006A36B0AEDE8D08E3753B1E002546A642A
    unencrypted_suffix: _unencrypted
    version: 3.12.2
