jobs:
- name: plan-branches
  plan:
  - get: non-main-branches
    trigger: true
  - file: non-main-branches/branches.json
    load_var: branches
  - across:
    - max_in_flight: 3
      values: ((.:branches))
      var: branch
    config:
      image_resource:
        name: ""
        source:
          repository: hashicorp/terraform
          tag: "1.10"
        type: registry-image
      params:
        AWS_ACCESS_KEY_ID: ((terraform.minio_access_key))
        AWS_SECRET_ACCESS_KEY: ((terraform.minio_secret_key))
        TF_VAR_proxmox_api_token: ((terraform.proxmox_api_token))
      platform: linux
      run:
        args:
        - -ec
        - |
          git clone https://github.com/peteches/guix \
            --branch ((.:branch.name)) \
            --depth 1 \
            repo
          cd repo/infra/terraform
          terraform init
          terraform plan
        path: sh
    task: plan-branch
- name: plan-main
  plan:
  - get: repo-main
    trigger: true
  - config:
      image_resource:
        name: ""
        source:
          repository: hashicorp/terraform
          tag: "1.10"
        type: registry-image
      inputs:
      - name: repo-main
        path: repo
      params:
        AWS_ACCESS_KEY_ID: ((terraform.minio_access_key))
        AWS_SECRET_ACCESS_KEY: ((terraform.minio_secret_key))
        TF_VAR_proxmox_api_token: ((terraform.proxmox_api_token))
      platform: linux
      run:
        args:
        - -ec
        - |
          cd repo/infra/terraform
          terraform init
          terraform plan
        path: sh
    task: plan
- name: apply-main
  plan:
  - get: repo-main
    passed:
    - plan-main
    trigger: true
  - config:
      image_resource:
        name: ""
        source:
          repository: hashicorp/terraform
          tag: "1.10"
        type: registry-image
      inputs:
      - name: repo-main
        path: repo
      params:
        AWS_ACCESS_KEY_ID: ((terraform.minio_access_key))
        AWS_SECRET_ACCESS_KEY: ((terraform.minio_secret_key))
        TF_VAR_proxmox_api_token: ((terraform.proxmox_api_token))
      platform: linux
      run:
        args:
        - -ec
        - |
          cd repo/infra/terraform
          terraform init
          terraform apply -auto-approve
        path: sh
    task: apply
resource_types:
- name: git-branches
  source:
    repository: aoldershaw/git-branches-resource
  type: registry-image
resources:
- name: non-main-branches
  source:
    branch_regexp: ^(?!main$).*
    uri: https://github.com/peteches/guix
  type: git-branches
- name: repo-main
  source:
    branch: main
    paths:
    - infra/terraform/
    uri: https://github.com/peteches/guix
  type: git
