jobs:
- name: plan-branches
  plan:
  - get: non-main-branches
    trigger: true
  - get: repo-main
    trigger: false
  - load_var: branches
    file: non-main-branches/branches.json
  - across:
    - var: branch
      values: ((.:branches))
      max_in_flight: 3
    task: plan-branch
    file: repo-main/ci/tasks/terraform-plan-branch.yml
    params:
      BRANCH_NAME: ((.:branch.name))
      AWS_ACCESS_KEY_ID: ((terraform.minio_access_key))
      AWS_SECRET_ACCESS_KEY: ((terraform.minio_secret_key))
      TF_VAR_proxmox_api_token: ((terraform.proxmox_api_token))

- name: plan-main
  plan:
  - get: repo-main
    trigger: true
  - task: plan
    file: repo-main/ci/tasks/terraform-plan.yml
    params:
      AWS_ACCESS_KEY_ID: ((terraform.minio_access_key))
      AWS_SECRET_ACCESS_KEY: ((terraform.minio_secret_key))
      TF_VAR_proxmox_api_token: ((terraform.proxmox_api_token))

- name: apply-main
  plan:
  - get: repo-main
    passed:
    - plan-main
    trigger: true
  - task: apply
    file: repo-main/ci/tasks/terraform-apply.yml
    params:
      AWS_ACCESS_KEY_ID: ((terraform.minio_access_key))
      AWS_SECRET_ACCESS_KEY: ((terraform.minio_secret_key))
      TF_VAR_proxmox_api_token: ((terraform.proxmox_api_token))

resource_types:
- name: git-branches
  source:
    repository: aoldershaw/git-branches-resource
  type: registry-image

resources:
- name: non-main-branches
  source:
    branch_regexp: ^(?!main$).*
    uri: https://github.com/peteches/guix
  type: git-branches

- name: repo-main
  source:
    branch: main
    paths:
    - infra/terraform/*
    - ci/tasks/*
    uri: https://github.com/peteches/guix
  type: git
