ssh-private-key: ENC[AES256_GCM,data:C38ccDc6Tz+Txr78AV/C+INdsRGDxnYqq/zKI/au5mH8BRgLHtwyZMezKv65C7Y5fwEcutE2kfwm4vH+2hjM/lHXoj1g9e+pxGpNNQkrZPEWvv3MV7/MMZRLMgdJwtkZCbWO49NQHkhdD/hCEeTDmB6+4NnGjJtRAzKYOVEOYnMH2d3BHLf2H7/wraBjLpsBBWj2PSZUFJpffE6Pu4q87tDbAc3mVHP3AMUT+w/uBxGDwbZQfhZsBjHKMd0zcFS69VO3oSwSUnQUt79GsOiDuSHcJLUlyAXtREcs9e/jFmOo75bkklQ2KbAJ5gQcJX0zFxTLC65EsQmkxE82nb7jvuISmrLMaVvNH5jWJTxJFk+k2NiPpNXQ5xQ1V1LE1oIRjkQ8jdNNR5WdrPF59SsQCrlbm+Q0q2q349JaiOrKa+Ytj8nhJDnNSlaR8qDsnx2WI4Zp5hKh9xSf1k1ROV5GQvChobYnVsRbmlvr+wWp3P/GtdjbWhMzdF4dSj8jx2pnusPHreg89v+Ymaks/ShavNYsbqzxOyzmu9ddwxkXy09hmF0=,iv:EoALioXrlQW2zW44mZo7wByqwjqau8PL6GmFptRwe3I=,tag:yuXF0fvRV2F3xIkkIc+K/Q==,type:str]
sops:
    age:
        - recipient: age15pfq0a37378fv4s2htwyzsdavksjyfq2mvmz62sk65fxpt4qqu4s7xyjpz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrL1NsaWluWlhoMTVnR1gz
            Y2VmV1Axbi8vV3pHblBVUWhiNC9JU2pOZkVzCldxMU43SnZ3SThDN2FJbHlGcXFX
            NnNiQ2JaM05lQitEcnZRNHk1c1R4RTAKLS0tIDZoQmtPQVI2UWlIdTZMSDN6YnBH
            b3pBVzhTSGNrV0VoLzdCV1lUVEFJRGsK4frSrMibZ+bqkudkq136Vi1Qdb7SA6tN
            bafIsw2e5KutlBC8LOsoYnRZZ8AfyzKgscIAZJS2rmFnBDwtTq5JtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T08:49:02Z"
    mac: ENC[AES256_GCM,data:hL0y5B7XrGbVnwRKU6U4XcYUT2BzGJ+gip1gjRWkFknbQ9xNsJHb0a+e05kRS8Jy7GCSFyHkpwdXIOhqcUcx0pUVNhJ3HUqpN5swHj1M0UyaAyOV1oUCDHo3ik4BwTSLwviJJCV8oKzT+9+MJ18uaOO/5LqwMkjxZUeOWz6BjXM=,iv:r30qyN7tl7kIel0okI0zghYNkhzkOVULevAnvBCHYmM=,tag:9FV7cUcNF3Q0QW9FPgjJkw==,type:str]
    pgp:
        - created_at: "2026-06-05T08:49:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5I9ZVut4Oz4SAQdAlvuSmWcf5zenpdf5iLwvCTI8lnO+FKzdYYrEEVlLqVkw
            anDmt3jMg5r405ij/PzUf4oxHIGJxazJDK7yXOL1AkFq3vhwyiR42eku3NetOyvb
            1GgBCQIQS2rjMaqFsSWkHM7aDYqTnd8gB/gScAkoDl3sFSDWQR0YuCqzQy0YniHg
            enwyghyeDWujVNmGSSOHSkvlhWe/+9K64b7Lec/dOsUtyHa4pe1bAzuz3bd5cDyu
            WgPznOmq1ykCoA==
            =ElYK
            -----END PGP MESSAGE-----
          fp: 5FFB7006A36B0AEDE8D08E3753B1E002546A642A
    unencrypted_suffix: _unencrypted
    version: 3.12.2
