password: ENC[AES256_GCM,data:+/S6NhKJ+fi6Ixqq5mLOY2QYPFNvrH+zZ+SSBEKUfssEy4CH3JelTf1Lmfn1r0C5ukdw/3gndWIzZWlM2Uc72w==,iv:98yEX5XQMqNwjNaYRPipuiJEvGiLNUk2EIel4ncOxqI=,tag:kEQCFK4f8qD8A90hyRldPw==,type:str]
ssh-key: ENC[AES256_GCM,data:ue+3YvVTFTc/whLUnrmyiuqAONQ/Kp+/QiSsjNOX/xtlwHj77QiKBB9oxaTFeP2pAauTxaF7aekKfzOmONazNk0I1sTF1G+9gZY16416vrvZjPsIVOTdcU86o2YiFwfPOLgIJGxLW8I25TwgSnFaME8+RKaGqZWKKeIUHiojWHuwBPLZCB/wf8k2QbEWRab2VhzQVJKhqK+Nwre8Iy7XffC9Q3uZuQwQ0Of2zft7XKaDFZbPd17PSevfikRNg5D6lkdlW0Xt4BFfd41ItErlQS4nNRAf/Sr4mHEukebg0se94ZoxowHLQpivn/NOvcHqZlTapnWWvTnRp725tikWMATsjGIvjTNDT2Rec64RO/twvwE6Z6F9pEhDZsRJ7ozshexnENAufwXluACxs8YtNFJUzU4EBRGTM3jUglkM0/m3+Ls8qD5eu+dp9uFoyGCKmk/rpPA4wyDYsXGgr4/85TXYG0Ku8IbgPUrgHc7PUUkaWo3rLCM/0vL0kim82TerKFlmtNXxp2t1MrKhGh9XytfbOEH47Te5XQAnF7a5keGXvswm1DigYAfnNRL9eUz/,iv:B5uR3OvzEPvft+LdklIsdjWUNg5toBX8Kea/RxJH8us=,tag:+JEPtkbdt7GbLS9OlbMfLQ==,type:str]
sops:
    age:
        - recipient: age15pfq0a37378fv4s2htwyzsdavksjyfq2mvmz62sk65fxpt4qqu4s7xyjpz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dkwvRDBwdW5DOFN6OGpq
            aUE2enZvZDBQRk10d2IwaDNza0g0TmhiVG5zCmd2ZFl1WUxCdHVOVFp1RGxmS2dH
            QWF1OU01N01aWVMxcmt0SlAyRHFWUncKLS0tIG5reFhXamx5aUJVd3ZPOVlITlpL
            d1ZLT3ROdUlZc3Rrd3owTkFnZnpVL3cKTuE7EZVGFBGCkFL+NkCqRH85Xu6h4Pe2
            7+40Iv+RIQoAX2cZt1kBOBvQRZzAfPVuIOS32Yd9XpN+QV/JrocV4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T17:57:19Z"
    mac: ENC[AES256_GCM,data:EdG+i/I3SAgkl+dy4zKWjViRE/IDUOdA3t4KPN4D3mYWdlSbVoKP0Yv0y1hJuCEL/yj6R4NeaSQYuTz8pTvwi/DE38UkYbPVXl96nyA9BnmQGF5oWDs7sTs72tKF+WYqig/d3lftz3h0nbjG/G/8x9acMl9HACh0gU2y7SZkrQ0=,iv:fR5TVlI+d+t5CzaGAseObsPYnp8xG3RZbpiQEEoCtW0=,tag:EOs7LQZJhq93OuES+MBABw==,type:str]
    pgp:
        - created_at: "2026-05-28T17:57:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5I9ZVut4Oz4SAQdAgSxYlOpUqvtjo1GFCICodCkh2etN291KNf4z0yCoD0Ew
            uS3P9UV9oUOhdekcRnxv2d4bWIb7wqqanta0VcrUHDn+xol0AE/n32IheH4mHXPq
            1GgBCQIQQF88aWJq/ycJsx0oc6hfkfF7VE68N/Rx/iG7CEJwIBishWqEzEko7EYG
            L0FZM7yxyN9coD0ThFwfDjPqALkBsr8a7VtqiTucBZOLJwMpcLpOsHgBfX0G5i5g
            8RjbC/zrYwWLFg==
            =cfEU
            -----END PGP MESSAGE-----
          fp: 5FFB7006A36B0AEDE8D08E3753B1E002546A642A
    unencrypted_suffix: _unencrypted
    version: 3.12.2
