restic-password: ENC[AES256_GCM,data:9bn8z5vh2qPwKsWwXbf4+Ml/OHNMyobkNTBNUrXT8S+5rzzvlhUO4sNAsmuLudd2mC1Tb1LP/QiSfoIS69xgxw==,iv:oJlcbWrQk8H91Qgzw69t79qI+yUuc4TETrdoYRQ1dxM=,tag:qGgkiKa5PGdFDp5X+7/ahg==,type:str]
ssh-key: ENC[AES256_GCM,data:GhIr4/NJSQ8qsGHowSBLYSsUjzbWTdnw26Ww4riSYrgEixILd/F/8d9kXaf2c8qwgs4TOF57CvkrgjmMglXIcBezOJeB8SDscFTzEqeNPrA9AI6vUiT59UnYnoJ9Kr/uh/sofzHkQHR31LdJ9rOIpGZBGtRVwKIZsyeaaeBa7ZpE06/LZWJcaVKN4rGnpte5HkuEBTHpy6thL80Mh+z9u22HrFlxJPPEwZIy8a2JcgfmOJaKx+kbQLo7b1QE0dL4VZgXQd4wOcRW72EAB4zk53LuFPj/ZkHapyUfZyvDj5o7Pnz9Omdp+tfPXSful8YJUHzfOZCIYLXIHIDPIUCoVIDsahQiY/pJPvc0TcKY441xvUYmT0hyyf08OoQuqZwf3FOJWT3+DSvVuBiSOQk+P4QXis7Q0Xe4r/4LXTQqQjdG1NOJN1MIyRFeAhFwHq52vdyPAyEnNSiocklmnWWoOggsPQieyOiPoMDPYSlCRJA+v9BF1Jvtg8yRsbMvLatBzcf9fcINtb/nxxqmvt//TV6+on25zFem1BJeZpLwcqEuvqInnUqwBxQChpxaryVs,iv:YDMlDkfPlYVolhbwOAot+WtBYdVmRSz6O6aEAKmPgN0=,tag:btwC9CjiZb+dkwaiOJPr7A==,type:str]
sops:
    age:
        - recipient: age15pfq0a37378fv4s2htwyzsdavksjyfq2mvmz62sk65fxpt4qqu4s7xyjpz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0c0VrSVdCVERrSnF2ekM2
            aldiYUUxM2lremt5Yy92WndoYkVBQktuQkM0CjNLczMzTUZRS1VJdkZzRkRGUnY0
            WFNPbFdrNCt0aUVrdTlUTWJqTW1MdDAKLS0tIGQ2MU8vWmQva2IrN2N3SFExVzFG
            ck10NzB5SHRNQ0FEVkxxYkRHWU5QcVUKyraWJ2MI3saxljSxtUMJUDYftnfmiCsL
            kLg+HRawJCWleZi9kvntZHM9l80jwrO57DXiOl9ScPOgcRfKFGslCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T11:37:52Z"
    mac: ENC[AES256_GCM,data:cQwS53V+Ugsyj3YGhZV+BRLfHqePrTb01RUnKupQ87MFeH0Jv2EziR0UmxYVp2k6olyJEGZZ2jG5G5pX1qRfawtMLenBoktJ/5Zsr95tD8GlL+PCVM3Y1QSIQZubre89uLMQBm5nKlB3K1almYLqL5PHfVf2uxNUbOSppw4ex6E=,iv:z5B2gMnvXI9C88mWSRzpWFfUcurb1HBrA+7wTwNu8U0=,tag:5F9O4Bkj6SDNF3ztRINrRQ==,type:str]
    pgp:
        - created_at: "2026-05-27T11:37:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5I9ZVut4Oz4SAQdAKJPG2encXWyT+zKz5ciIUKK7vmimVTPR4ZR3IdwBtVAw
            NW/G323Q4vNpoSIBfOd7+sfjYg6elifXHLf/fLlsm9fAbsMqFVeXcQUiWB3UmglR
            1GgBCQIQAPIliuMT5QCIIbwhjFNZhEy+Juagqx3SodgkWXtnPK7bkh81dGiKPds3
            Zh+fCHglh4Xgrhl/L7tIf0IKdT3hd+Ymszgq91uy6y+faoTMeZRSevwI3kOhph4/
            V+cj5LmxgW6gxg==
            =KRFG
            -----END PGP MESSAGE-----
          fp: 5FFB7006A36B0AEDE8D08E3753B1E002546A642A
    unencrypted_suffix: _unencrypted
    version: 3.12.2
