# Generated by matugen — do not edit directly.
MATUGEN_PRIMARY={{colors.primary.default.hex_stripped}}
MATUGEN_ON_PRIMARY={{colors.on_primary.default.hex_stripped}}
MATUGEN_PRIMARY_CONTAINER={{colors.primary_container.default.hex_stripped}}
MATUGEN_ON_PRIMARY_CONTAINER={{colors.on_primary_container.default.hex_stripped}}
MATUGEN_SECONDARY={{colors.secondary.default.hex_stripped}}
MATUGEN_ON_SECONDARY={{colors.on_secondary.default.hex_stripped}}
MATUGEN_BACKGROUND={{colors.background.default.hex_stripped}}
MATUGEN_ON_BACKGROUND={{colors.on_background.default.hex_stripped}}
MATUGEN_SURFACE={{colors.surface.default.hex_stripped}}
MATUGEN_ON_SURFACE={{colors.on_surface.default.hex_stripped}}
MATUGEN_OUTLINE={{colors.outline.default.hex_stripped}}
