;; Generated by matugen — do not edit directly.
(let ((theme (make-instance 'theme:theme
                             :background-color "{{colors.background.default.hex}}"
                             :on-background-color "{{colors.on_background.default.hex}}"
                             :primary-color "{{colors.primary.default.hex}}"
                             :on-primary-color "{{colors.on_primary.default.hex}}"
                             :secondary-color "{{colors.surface_container.default.hex}}"
                             :on-secondary-color "{{colors.on_surface.default.hex}}"
                             :action-color "{{colors.primary.default.hex}}"
                             :highlight-color "{{colors.tertiary.default.hex}}")))
  (define-configuration browser
    ((theme theme)))
  (when (and (boundp 'nyxt:*browser*) nyxt:*browser*
             (slot-value nyxt:*browser* 'nyxt::ready-p))
    (setf (theme nyxt:*browser*) theme)))
